#!/usr/bin/perl -T -CSDAL
use warnings;
use strict;
use JSON;
use Path::Tiny;
use WWW::Curl::Easy;

my $ticket_id = $ARGV[0];

die "invalid ticket id!\n" if !defined $ticket_id || $ticket_id !~ /^\d{1,6}$/;

my $url = sprintf("https://redmine.iserv.eu/issues/%s.json", $ticket_id);
my $apikey = join "", path("~/.vim/iserv/redmine.auth")->lines_utf8({chomp=>1});

my $curl = new WWW::Curl::Easy;
$curl->setopt(CURLOPT_URL, $url);
$curl->setopt(CURLOPT_HTTPHEADER, ["Content-Type: application/json"]);
$curl->setopt(CURLOPT_USERPWD, $apikey.":x");
$curl->setopt(CURLOPT_WRITEDATA, \my $res);
my $err = $curl->perform;

if ($err != 0)
{
  print "CURL error $err!\n";
  exit 1;
}

if (defined $res)
{
  my $json = decode_json $res;

  my $displayname = $json->{issue}->{project}->{name}." - ".
      $json->{issue}->{tracker}->{name}." #".
      $json->{issue}->{id}.": ".
      $json->{issue}->{subject};
  print $displayname, "\n";
}
else
{
  print "not found!\n";
  exit 1;
}

