#!/bin/bash


profiles=$(pactl list sinks|grep "Name: "|cut -d':' -f2)

chosen=$(printf "%s" "$profiles" | dmenu -i -p "Select audio output") &&
	pactl set-default-sink $chosen

pkill -RTMIN+1 i3blocks
