#!/bin/sh
lockn() {
    killall compton
    i3lock -n -i ~/Pictures/lockscreen.png
    compton --config ~/.config/compton/compton.conf
}
lock() {
    i3lock -i ~/Pictures/lockscreen.png
}

case "$1" in
    lock)
        lockn
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        lock && systemctl suspend
        ;;
    hibernate)
        lock && systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
