#!/bin/sh
lockn() {
    trap revert HUP INT TERM
    killall compton || :
    xset +dpms dpms 5 5 5
    i3lock -n
    compton --config ~/.config/compton/compton.conf &
    revert

}
revert() {
	xset dpms 0 0 0
}
lock() {
    trap revert HUP INT TERM
    xset +dpms dpms 5 5 5
    i3lock -n
    revert
}

case "$1" in
    lock)
        lockn
        ;;
    logout)
        i3-msg exit
        ;;
    suspend)
        lock && systemctl suspend
        ;;
    hibernate)
        lock && systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
