#!/bin/bash

nmcli -t -f type,state,connection d | grep -q tun

if [ $? -eq 0 ]; then
	echo -n "<span color='#00ff00'>"
	echo -n [VPN]	
	echo "</span>"
else 
	echo -n "<span color='#ff0000'>"
	echo -n [VPN]
	echo "</span>"
fi
